-- 1. Таблица пользователей
create TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    birthday DATE NOT NULL
);

-- 2. Таблица фильмов
create TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    mpa_rating VARCHAR(10)
);

-- 3. Таблица жанров (соответствует enum Genre)
create TABLE IF NOT EXISTS genres (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- 4. Таблица связей фильмов и жанров
create TABLE IF NOT EXISTS film_genres (
    film_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES films(id) ON delete CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres(id)
);

-- 5. Таблица лайков
create TABLE IF NOT EXISTS likes (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES films(id) ON delete CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON delete CASCADE
);

-- 6. Таблица друзей с односторонней дружбой и статусами
create TABLE IF NOT EXISTS friends (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON delete CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users(id) ON delete CASCADE
);

-- 7. Индексы для оптимизации
create index IF NOT EXISTS idx_friends_friend_status ON friends(friend_id, status);